### ISSUE TITLE
Have a way to differenciate errors due to requests errors vs missing flags

### ISSUE THREAD

**Issue by AdrianB-sovo** [Flagsmith/flagsmith-python-client#65]
When doing:
```python
flags = flagsmith.get_environment_flags()
environment_flags.is_feature_enabled("foo")
```

- If the feature flag does not exist, the following error is raised: 
`FlagsmithClientError("Feature does not exist: <my_feature>")`
- If the environment failed to do an API request, the following error is raised: 
`FlagsmithClientError("Feature does not exist: <my_feature>")`

I would like to raise different alerts in those cases, because the fix to the problems are not the same (i.e., waiting for it to resolve itself vs adding the flag or removing the code using the flag).

Could we have a way to differentiate them?

### Suggestions
- Flags could have an attribute to store the fact that the Flags were created following a `FlagsmithAPIError`, then, different errors could be raised in `Flags.get_flag()` using this attribute.

or

- The `default_flag_handler()` could have a parameter that would indicate the type of error.

**Comment by matthewelwell** [comment]
Hi @AdrianB-sovo, thanks for this. It's an interesting point and I certainly understand the request. As per your first suggestion, I think that adding a parameter to the `Flags` object to indicate if the request to the API was successful or not would be the best way to solve this. 

Would you be up for submitting a PR for this? Otherwise we will add this to our backlog.

**Comment by tushar5526** [comment]
@matthewelwell I plan to work on this issue - is this still open or picked internally?

**Comment by matthewelwell** [comment]
@tushar5526 sure, it's still available to work on, let me know if you have any questions or need any guidance.

**Comment by tushar5526** [comment]
Hey @matthewelwell - I was trying to reproduce this, but it seems we raise a `FlagsmithAPIerror` at https://github.com/Flagsmith/flagsmith-python-client/blob/main/flagsmith/flagsmith.py#L339, hence the code will halt at `flags = flagsmith.get_environment_flags()`. 

It seems the above error is only reproducible in offline mode or local evaluation when the API call fails and we fallback to local evaluation or offline mode ?

**Comment by matthewelwell** [comment]
I'm sorry @tushar5526 , I'm struggling to understand what you're asking here. Can you illustrate with code / example scenarios perhaps? 

My understanding of this issue is that if, in any evaluation mode, you do something like the following, then a `FlagsmithClientError` is raised in all failure scenarios. What we'd like to happen is that, if flag `"foo"` does not exist, then a new exception is raised (e.g. `FlagDoesNotExist`). 

```
flags = flagsmith.get_environment_flags().is_feature_enabled("foo")
```

Are you saying that some part of this assumption is not correct?

**Comment by tushar5526** [comment]
Hey @matthewelwell 
> My understanding of this issue is that if, in any evaluation mode, you do something like the following, then a FlagsmithClientError is raised in all failure scenarios

Incase of network errors, it raises a `FlagsmithAPIError` instead of a `FlagsmithClientError`.

I have also attached screenshots below. I am using a basic Flagsmith cloud account. 

<img width="1440" alt="Screenshot 2024-06-11 at 7 06 13 PM" src="https://github.com/Flagsmith/flagsmith-python-client/assets/30565750/3ac5e8e1-7ac8-4540-a13c-43d16f5bece2">

**Client Error if I try to get status of a non-existing flag**

<img width="1440" alt="Screenshot 2024-06-11 at 7 06 29 PM" src="https://github.com/Flagsmith/flagsmith-python-client/assets/30565750/52c49a33-debe-4447-9ca4-0a7fc379345a">

**FlagsmithAPIError when I turn the wifi off**

If you follow through the implementation of `get_environment_flags` you will see it raises a the `FlagsmithAPIError` for network, therefore I thought the behaviour described in the issue would only be reproducible in local or offline mode.

**Comment by matthewelwell** [comment]
Gotcha, ok - so technically this issue could probably be resolved as 'cannot reproduce'... but, I do think that adding a new exception (that inherits from `FlagsmithClientError`) which is raised when a flag is not found could be a good addition still.
